### ISSUE TITLE
Does not work with Thunderbird 78

### ISSUE THREAD

**Issue by mind-bending-forks** [Meatian/confirm-address#49]
I upgraded to Thunderbird 78.1.1 (64-bit). This add-on stopped working.

- When I attempt to send an email to addresses outside the specified domain, no dialog is shown.
- The add-on shows as installed, but I can no longer find any way to configure it.

**Comment by jobisoft** [comment]
Hi,

Thunderbird has created a new staff position called "Add-on support engineer" - which happens to be me (John Bieling). In the last weeks I have worked on a shortcut update path, to get legacy extensions working in TB78 again, with the minimal amount of work possible. It is using an Experiment wrapper API:
https://github.com/thundernest/addon-developer-support/wiki

After the initial update, we can remove the legacy parts step by step. The idea is to get the add-on compatible as easy and as fast as possible and do the "full" conversion to a true MailExtension without Experiment APIs in smaller steps, while your users can already use your add-on in TB78.

I would love to see your add-on in TB78 and I offer help via our community channels:
https://developer.thunderbird.net/add-ons/community

Thank you for your contributions,
John

**Comment by ranman3g** [comment]
Really looking forward to seeing this updated for TB 78.2 (which has been an unmitigated disaster for almost all my add-ons).

**Comment by Meatian** [comment]
Hopefully I uploaded Confirm-Address 1.3.6 runs on Thunderbird 78.

**Comment by Meatian** [comment]
I've been reported an issue no recipients list is shown on confirm-address dialog on Thunderbird 78.1.1 which I (and some other people around me) couldn't reproduce.  The person also reported me nothing changed when Thunderbird is updated to 78.3.2.  Perhaps it's not Confirm-Address issue nor Thunderbird issue but I can't see what's wrong with it so far.
