### ISSUE TITLE
Not support  Thunderbird 78.4.0

### ISSUE THREAD

**Issue by hqshou2004** [Meatian/confirm-address#51]
![th](https://user-images.githubusercontent.com/7541437/96837600-453a9e80-1479-11eb-969e-5a15cdf594fb.png)

not support Thunderbird 78.4.0。

please help us. Thanks.

**Comment by Meatian** [comment]
It does run on Thunderbird 78.4.0. If your Confirm-Address was not version 1.3.6, please update it.

**Comment by hqshou2004** [comment]
It's OK.
Thank you!
